### ISSUE TITLE
Publish latest to PyPI

### ISSUE THREAD

**Issue by dpassen** [Python-Optional/optional.py#48]

**Comment by cbefus** [comment]
are these instructions still accurate: https://github.com/Python-Optional/optional.py/wiki/Publishing-to-Pypi

**Comment by dpassen** [comment]
I don't know lol

**Comment by cbefus** [comment]
I mean - specifically - is it still `poetry build`?  I can figure out pypi

**Comment by dpassen** [comment]
Yes. Still `poetry build`

**Comment by cbefus** [comment]
Done.

**Comment by cbefus** [comment]
This is done.
